name: house price
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          pip install --upgrade pip
          pip install -r requirements.txt
          python train.py
          echo "metrices added to report.md file"
          cat metrics.txt >> report.md
          echo "images added to report.md file"
          cml-publish feature_importance.png --md >> report.md
          cml-publish feature_importance1.png --md >> report.md
          cml-publish PearsonHeatMap.png --md >> report.md
          cml-publish MEDV.png --md >> report.md
          cml-publish feature_importance2.png --md >> report.md
          cml-publish feature_importance3.png --md >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          cml-send-comment report.md
